### PR TITLE
edited read me w/ tinder tokn

### PR DESCRIPTION
**Pull request by mrandrewandrade**

### CODE REVIEW

**Comment by ayancey** [comment]
This doesn't seem like much of an easier solution, to me. It's a good solution for people who aren't quick enough, though.

I wonder if we can trigger an actual login prompt. Does that require the client secret, @zachlatta?

**Comment by zachlatta** [comment]
Thanks for the PR @mrandrewandrade. Can you flow the text at 80 characters? After that, ready for merge.

@ayancey I figure more clarity is better. And yeah, I believe we'd need Tinder's secret to have our own login prompt.

**Comment by mrandrewandrade** [comment]
Sorry what does flow the text at 80 characters mean?

**Comment by zachlatta** [comment]
No worries!

Wrap is probably a more descriptive word. Essentially converting

```
Once there, go to your browser's developer console, click to the Network tab, and go to the above URL again. After the second traversal, you should see two network calls on the developer console. Click the first one and look at its response headers. There should be a "location" field in the header. The value of that field should contain an auth_token.
```

to

```
Once there, go to your browser's developer console, click to the Network tab,
and go to the above URL again. After the second traversal, you should see
two network calls on the developer console. Click the first one and look at
its response headers. There should be a "location" field in the header. The
value of that field should contain an auth_token.
```

**Comment by mrandrewandrade** [comment]
Ah I understand!

I will do that when I get back home, on my way to a tinder date

**Comment by zachlatta** [comment]
Sounds great! Good luck!

**Comment by mrandrewandrade** [comment]
Hey man, the date went well.  I came over to her house but was thinking about the PR so I taught her git and she helped me with the pull request.  I tried showing her VIM but she got discouraged and asked me to leave.  She said she likes github and might ask me to come over again sometime ;).

Anyways, we wrapped the text to 80 characters, but I was not sure about the link (in brackets) since it was long and it would break if I wrap.  Does that have to be wrapped as well?

**Comment by Dillybob1992** [comment]
"her VIM but she got discouraged and asked me to leave"

LOL

**Comment by zachlatta** [comment]
Going to close this PR due to lack of progress.

**Comment by Dillybob1992** [comment]
One of the best PR's I've ever seen. @mrandrewandrade Godspeed sir.

**Comment by jasonz130** [comment]
Sounds like you wrapped it up well!  lgtm

**Comment by mrandrewandrade** [comment]
Yeah we still keep it wrapped and it hasn't broken yet.  Been together almost 10 years, we just got engaged:
DSC05817

**Pull request merged**
